### ISSUE TITLE
🐛 Bug Report: TypeError: Cannot read properties of undefined (reading 'get')

### ISSUE THREAD

**Issue by nexmoe** [appwrite/demo-todo-with-vue#37]
### 👟 Reproduction steps

Refresh the page after login

### 👍 Expected behavior

Stay logged in

### 👎 Actual Behavior

I need to log in again

And I caught possible related errors

```
TypeError: Cannot read properties of undefined (reading 'get')
    at Object.getAccount (index.js:25:34)
    at Store2.fetchAccount (account.js?t=1660704707512:29:33)
    at Array.wrappedActionHandler (vuex.esm-bundler.js:305:23)
    at Store2.dispatch (vuex.esm-bundler.js:1032:13)
    at Store2.boundDispatch [as dispatch] (vuex.esm-bundler.js:914:21)
    at Proxy.mappedAction (vuex.esm-bundler.js:1281:20)
    at Proxy.created (App.vue:27:12)
    at callWithErrorHandling (runtime-core.esm-bundler.js:155:36)
    at callWithAsyncErrorHandling (runtime-core.esm-bundler.js:164:21)
    at callHook (runtime-core.esm-bundler.js:2965:5)
```

### 🎲 Appwrite version

Version 0.10.x

### 💻 Operating system

Windows

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by nexmoe** [comment]
The session is saved in local storage, but it does not work

**Comment by hannesfant** [comment]
Mind if I hop on this?

**Comment by stnguyen90** [comment]
@hannesfant are you still interested on working on this?

**Comment by 1-ankush-1** [comment]
Can i take this issue as hacktoberfest.

**Comment by Haimantika** [comment]
> Can i take this issue as hacktoberfest.

Hi @1-ankush-1 have assigned the issue to you! Thank you for showing interest in contributing to Appwrite! Happy Hacktoberfest 🎃

Notes:
1. Please update us with your progress every 3 days, so that we know that you are working on it.
2. Join us on Discord - https://appwrite.io/discord to chat about Hacktoberfest and Appwrite!

**Comment by Vaibhav91one** [comment]
@Haimantika do assign me the issue, if the issue is not solved.

**Comment by 1-ankush-1** [comment]
Hey @Haimantika  when i try to run the demo vercel application it is working fine . 

https://github.com/appwrite/demo-todo-with-vue/assets/95346389/db8d54d4-7230-4096-9efe-5ddec1330125

🤔 Doubt 
If i want to run this application in local env . I need a url to connect to the server how can i get that.
 
💻 Operating system
Windows

🌐 Browser
Chrome and Edge

**Comment by aryanarayantiwari** [comment]
Hi @1-ankush-1 are you still working on the issue ? If not I would request @Haimantika to assign the the issue to me if possible ?

**Comment by 1-ankush-1** [comment]
> Hi @1-ankush-1 are you still working on the issue ? If not I would request @Haimantika to assign the the issue to me if possible ?
you can ask her to assign this issue to you.

**Comment by aryanarayantiwari** [comment]
> > Hi @1-ankush-1 are you still working on the issue ? If not I would request @Haimantika to assign the the issue to me if possible ?
> you can ask her to assign this issue to you.

Thanks, @Haimantika can you please assign me this issue ?

**Comment by Haimantika** [comment]
> Hi @1-ankush-1 are you still working on the issue ? If not I would request @Haimantika to assign the the issue to me if possible ?
> you can ask her to assign this issue to you.

Hi @1-ankush-1 will you not be working on it? I somehow cannot see your message, thus double checking.

**Comment by Haimantika** [comment]
Hi @1-ankush-1 we will be reassigning the issue from you to the next person soon due to inactivity from your end.

**Comment by aryanarayantiwari** [comment]
Hi @Haimantika Please take a look at the attached screenshot. It was all a issue of formatting.
![IMG_20231020_000119](https://github.com/appwrite/demo-todo-with-vue/assets/67976672/b3ba5086-1ef8-4c33-b94e-85f9e963e505)
